language: ruby
dist: focal
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.4.10
  - 2.5.9
  - 2.6.8
  - 2.7.4
  - 3.0.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem update --system 2.1.11
  - git config --global user.email 'user@example.com'
  - git config --global user.name 'Test User'
